---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: test-ecr-repo
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: 367941558016.dkr.ecr.us-east-1.amazonaws.com/test-ecr-repo:latest
        ports:
        - containerPort: 80
          name: website
