---
apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: backend-service
    labels:
        app: website
spec:
    type: LoadBalancer
    selector:
        app: website
    ports:
#     - nodeport: 31479
      port: 80
      protocol: TCP  
      targetPort: 3000
